jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.11.0"
      - run: "rm -rf .husky"
      - run: "npm ci"
      - env:
          GIT_AUTHOR_EMAIL: 12670155+calmery@users.noreply.github.com
          GIT_AUTHOR_NAME: calmery
          GIT_COMMITTER_EMAIL: 12670155+calmery@users.noreply.github.com
          GIT_COMMITTER_NAME: calmery
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
        run: "npx semantic-release"

name: Release

on:
  push:
    branches:
      - main
